#!/usr/bin/env bash


playlist() {
    jq -r '.data | to_entries[] |  [.key, .value.title, .value.filename] | map(values) | @tsv' <<< $playlist \
        | sort -bk2,2 -t $'\t'
}

channels_in_playlist() {
    jq '[.data[] | .title | values]' <<< "$playlist"
}

tvprog() {
    if [[ -z $epg ]]; then
        return
    fi
    # shellcheck disable=SC2016
    query_tvprogs='
    (input | .tv) as $tv
    | (input | .[]) as $channel
    | first($tv.channel[]
    | select(.["display-name"][]
        | [if type == "object" then .["#text"] end]
        | any(. == $channel))
    | {name: $channel, id: .["@id"]})
    | . as $ch
    | [$ch.name, ($tv.programme[]
        | select(.["@channel"] == $ch.id and .["@stop"] >= (now | strflocaltime("%Y%m%d%H%M%S %z")))
        | [(.title | if type == "object" then .["#text"] end), (.["@start"] | strptime("%Y%m%d%H%M%S %z") | mktime | strftime("%H:%M"))])][:3]
    | .[1][1] |= empty | flatten | @tsv'

    jq -nr "$query_tvprogs" "$epg" <(channels_in_playlist) | sort -bk1,1 -t $'\t'
}

join_tvprog_and_playlist() {
    join -a 1 -1 2 -t $'\t' <(playlist) <(tvprog) \
        | awk -F'\t' 'BEGIN{OFS="\t"} {tmp=$1; $1=$2; $2=tmp; print}' | column -t -s $'\t'
}

print_usage() {
cat >&2 <<END
Jump between mpv playlist entries using fzf.

You can optionally pass an epg in xmltv format to see the current tv programs.

Usage: $myname
       $myname https://example.com/epg.xml.gz
       $myname /path/to/epg.json
END
}

mpvsocket=${IPC_SOCKET:-/tmp/mpvsocket}
myname=${0##*/}

reload=""
epg=""
if [[ $# -eq 1 && ($1 == "--help" || $1 == "-h") ]]; then
    print_usage
    exit
elif [[ $# -ge 1 && $1 == "reload" ]]; then
    reload=yes
    if [[ $# -gt 1 ]]; then
        epg=$2
    fi
elif [[ $# -eq 1 ]]; then
    epg=$1
elif [[ $# -ne 0 ]]; then
    print_usage
    exit 1
fi

playlist=$(socat - "$mpvsocket" <<< '{"command": ["get_property", "playlist"]}')
# shellcheck disable=SC2181
if [[ $? != 0 ]]; then
    echo "Can't connect to mpv" >&2
    exit 1
fi
err=$(jq -r .error <<< "$playlist")
if [[ $err != "success" ]]; then
    [[ "$err" ]] && echo "mpv error: $err" >&2
    exit 1
fi

if [[ $reload ]]; then
    join_tvprog_and_playlist
    exit
fi

fzf --layout=reverse-list --with-nth=2.. \
    --bind "start,ctrl-r:reload:${0@Q} reload ${epg@Q}"  \
    --bind 'enter:execute-silent:socat - '"$mpvsocket"' <<< "{ \"command\": [\"playlist-play-index\", "{1}"] }" > /dev/null'



