#!/usr/bin/env bash

# Copyright 2026 wpdevelopment11
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

playlist() {
    local playlist_query
    if [[ -z $epg ]]; then
        playlist_query='.data | to_entries[] | [.key, .value.title // (.value.filename | split("/")[-1] | split(".") | if length > 1 then .[0:-1] end | join(".")), .value.filename] | map(values) | @tsv'
    else
        # Don't show an entry filename with an epg, it will clutter the output
        playlist_query='.data | to_entries[] |  [.key, .value.title // ("Error! Entry title is empty.", .value.filename)] | @tsv'
    fi
    jq -r "$playlist_query" <<< "$playlist" | sort -bk2,2 -t $'\t'
}

channels_in_playlist() {
    jq '[.data[] | .title | values]' <<< "$playlist"
}

tvprog() {
    # shellcheck disable=SC2016
    local epg_query='
    ([label $stop | inputs
      | if .["@id"] != null then
          .["display-name"][] as $display_name | $playlist_channels[0][] as $name | select(($display_name | if type == "object" then $display_name.["#text"] end) == $name) | {key: .["@id"], value: $name}
        else
          break $stop
        end
    ] | from_entries) as $channels | (now | strflocaltime("%Y%m%d%H%M%S %z")) as $now | label $stop2 | reduce inputs as $program ({};
        $program.["@channel"] as $channel | if (. | length) == ($channels | length) then
            .
        elif ($channels | has($channel)) and (. | has($channel) | not) and ($program.["@stop"] >= $now) then
            .[$channel] |= [$channels[$channel], $program, input]
        else
            .
        end) | .[] | [.[0], (.[1,2].title | if type == "object" then .["#text"] end), (.[2]["@start"] | (if . != null then strptime("%Y%m%d%H%M%S %z") | mktime | strftime("%H:%M") end))] | @tsv'

    jq -nr --slurpfile playlist_channels <(channels_in_playlist) "$epg_query" <(gzip -cdf "$epg") | sort -bk1,1 -t $'\t'
}

join_tvprog_and_playlist() {
    join -a 1 -1 2 -t $'\t' <(playlist) <(tvprog) \
        | awk -F'\t' 'BEGIN{OFS="\t"} {tmp=$1; $1=$2; $2=tmp; print}'
}

playlist_table() {
    if [[ -z $epg ]]; then
        echo $'ID\tTitle\tPath'
        playlist
    else
        echo $'ID\tChannel\tCurrent program\tNext program\tStart'
        join_tvprog_and_playlist
    fi | column -t -s $'\t'
}

fetch_url() {
    local resp
    resp=$(curl "$@" -fL -o "$epg_temp" -w '%{response_code} %{header_json}' "$url")
    status=$?
    response_code=${resp%%\ *}
    headers=${resp#*\ }
    return $status
}

epg_to_json() {
    echo "Converting xmltv to json..." >&2
    # shellcheck disable=SC2016
    conv_query='(now | strflocaltime("%Y%m%d%H%M%S %z")) as $now | .tv.channel[],null,([.tv.programme[] | select(.["@stop"] >= $now)] | sort_by(.["@channel"], .["@stop"]) | .[])'
    gzip -cdf "$1" | "$xq" -c --xml-force-list display-name "$conv_query" - | gzip > "$2"
}

save_result() {
    epg_to_json "$epg_temp" "$epg_path"
    cat <<< "$headers" > "$epg_headers_path"
}

handle_url() {
    local url=$1

    local urlhash
    urlhash=$(sha256sum <<< "$url" | awk '{print $1}')
    local urldir=$cache_dir/$urlhash
    mkdir -p "$urldir"

    local epg_temp
    epg_temp=$(mktemp)
    trap 'rm -f "$epg_temp"' RETURN

    local epg_headers_path=$urldir/headers.json
    local epg_path=$urldir/epg.json.gz

    local headers response_code
    if [[ ! (-f $epg_headers_path && -f $epg_path) ]]; then
        if ! fetch_url; then
            return 2
        fi
        save_result
        epg=$epg_path
    else
        # Check for updates for an already existing epg
        local etag last_modified
        etag=$(jq -r '.etag[0] // ""' "$epg_headers_path")
        last_modified=$(jq -r '.["last-modified"][0] // ""' "$epg_headers_path")
        if [[ $etag ]]; then
            local etag_file
            etag_file=$(mktemp)
            trap 'rm -f "$epg_temp" "$etag_file"' RETURN
            cat <<< "$etag" > "$etag_file"
            fetch_url "--etag-compare" "$etag_file"
        elif [[ $last_modified ]]; then
            fetch_url "--time-cond" "$last_modified"
        else
            # etag and the last-modified time is not known,
            # gave up and download the epg again
            fetch_url
        fi

        fetch_status=$?
        epg=$epg_path

        if [[ $fetch_status -ne 0 ]]; then
            return 1
        fi

        if [[ $response_code -ne 304 ]]; then
            save_result
        fi
    fi
}

print_usage() {
cat >&2 <<END
Switch between mpv playlist entries using fzf.

You can optionally pass EPG in XMLTV format to see the current TV programs.

Usage: ${0##*/} [ EPG_URL | EPG_PATH ]
END
}

cache_dir=${XDG_CACHE_HOME:-~/.cache}/mpv-fzf-playlist
mpvsocket=${IPC_SOCKET:-/tmp/mpvsocket}

reload=""
epg=""
if [[ $# -eq 1 && ($1 == "--help" || $1 == "-h") ]]; then
    print_usage
    exit
elif [[ $# -ge 1 && $1 == "reload" ]]; then
    reload=yes
    if [[ $# -gt 1 ]]; then
        epg=$2
    fi
elif [[ $# -eq 1 ]]; then
    epg=$1
elif [[ $# -ne 0 ]]; then
    print_usage
    exit 1
fi

if [[ -n $epg ]]; then
    if command -v xq &> /dev/null; then
        xq=xq
    elif command -v xq-python &> /dev/null; then
        xq='xq-python'
    else
        echo 'xq is not found in the PATH' >&2
        exit 1
    fi
fi

if [[ $epg =~ ^https?:// ]]; then
    handle_url "$epg"
    status=$?
    if [[ $status -eq 1 ]]; then
        echo "Error while trying to update the epg. Using the old one." >&2
    elif [[ $status -eq 2 ]]; then
        echo "Error while fetching url: $epg" >&2
        # Can't recover from this
        exit 1
    fi
elif [[ $epg =~ \.xml(\.gz)?$ ]]; then
    converted=$(mktemp --suffix=.json.gz)
    trap 'rm -f "$converted"' EXIT
    epg_to_json "$epg" "$converted"
    epg=$converted
fi

playlist=$(socat - "$mpvsocket" <<< '{"command": ["get_property", "playlist"]}')
# shellcheck disable=SC2181
if [[ $? -ne 0 ]]; then
    echo "Can't connect to mpv. You run mpv with the --input-ipc-server option set. Right?" >&2
    exit 1
fi
err=$(jq -r .error <<< "$playlist")
if [[ $err != "success" ]]; then
    [[ "$err" ]] && echo "mpv error: $err" >&2
    exit 1
fi

if [[ $reload ]]; then
    playlist_table
    exit
fi

fzf --layout=reverse-list --with-nth=2.. --header-lines=1 --cycle \
    --bind "start,ctrl-r:reload:${0@Q} reload ${epg@Q}"  \
    --bind 'enter:execute-silent:socat - '"$mpvsocket"' <<< "{ \"command\": [\"playlist-play-index\", "{1}"] }" > /dev/null'
