#!/bin/bash

epg=epg.json
mpvsocket=/tmp/mpvsocket

playlist() {
    jq -r '.data | to_entries[] |  [.key, .value.title, .value.filename] | map(values) | @tsv' <<< $playlist \
        | sort -bk2,2 -t $'\t'
}

channels_in_playlist() {
    jq '[.data[] | .title | values]' <<< $playlist
}

tvprog() {
    query_tvprogs='
    (input | .tv) as $tv
    | (input | .[]) as $channel
    | first($tv.channel[]
    | select(.["display-name"][]
        | [if type == "object" then .["#text"] end]
        | any(. == $channel))
    | {name: $channel, id: .["@id"]})
    | . as $ch
    | [$ch.name, ($tv.programme[]
        | select(.["@channel"] == $ch.id and .["@stop"] >= (now | strflocaltime("%Y%m%d%H%M%S %z")))
        | [(.title | if type == "object" then .["#text"] end), (.["@start"] | strptime("%Y%m%d%H%M%S %z") | mktime | strftime("%H:%M"))])][:3]
    | .[1][1] |= empty | flatten | @tsv'

    jq -nr "$query_tvprogs" "$epg" <(channels_in_playlist) | sort -bk1,1 -t $'\t'
}

join_tvprog_and_playlist() {
    join -a 1 -1 2 -t $'\t' <(playlist) <(tvprog) \
        | awk -F'\t' 'BEGIN{OFS="\t"} {tmp=$1; $1=$2; $2=tmp; print}' | column -t -s $'\t'
}

playlist=$(socat - "$mpvsocket" <<< '{"command": ["get_property", "playlist"]}')
if [[ $? != 0 ]]; then
    echo "Can't connect to mpv" >&2
    exit 1
fi
err=$(jq -r .error <<< $playlist)
if [[ $err != "success" ]]; then
    [[ "$err" ]] && echo "mpv error: $err" >&2
    exit 1
fi

if [[ $1 == "reload" ]]; then
    join_tvprog_and_playlist
    exit
fi

fzf --layout=reverse-list --with-nth=2.. \
    --bind "start,ctrl-r:reload:$0 reload" \
    --bind 'enter:execute-silent:socat - '"$mpvsocket"' <<< "{ \"command\": [\"playlist-play-index\", "{1}"] }" > /dev/null'



